# Generated by Django 5.1.15 on 2026-03-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('member', 'Member'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
