# Generated by Django 5.1.15 on 2026-03-20 09:44

from django.db import migrations


def convert_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Convert existing manager users to member
    User.objects.filter(role='manager').update(role='member')
    # Promote first admin user to super_admin
    first_admin = User.objects.filter(role='admin').order_by('id').first()
    if first_admin:
        first_admin.role = 'super_admin'
        first_admin.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(convert_roles, migrations.RunPython.noop),
    ]
