# Generated by Django 5.1.15 on 2026-03-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=5)),
                ('pin_code', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('pan', models.CharField(blank=True, default='', max_length=10)),
                ('customer_type', models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Distributor', 'Distributor'), ('Industrial', 'Industrial')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('used_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_terms_days', models.IntegerField(default=30)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ytd_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_year_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('ytd_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_tier', models.CharField(choices=[('standard', 'Standard'), ('wholesale', 'Wholesale'), ('premium', 'Premium'), ('vip', 'VIP')], default='standard', max_length=20)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('first_order_date', models.DateField(blank=True, null=True)),
                ('credit_status', models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('blocked', 'Blocked'), ('review', 'Review')], default='good', max_length=20)),
                ('payment_behavior', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=20)),
                ('days_since_last_payment', models.IntegerField(default=0)),
                ('gst_amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tds_amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('branch_name', models.CharField(blank=True, default='', max_length=100)),
                ('financial_notes', models.TextField(blank=True, default='')),
                ('credit_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='customers.customer')),
            ],
            options={
                'db_table': 'financials',
            },
        ),
    ]
